export default Object.freeze({
  LISTING_DETAILS: "ListingDetails",
  LISTING_EDIT: "ListingEdit",
  LOGIN: "Login",
  MESSAGES: "Messages",
  REGISTER: "Register",
  USER_S: "User",
  Free_S: "Free",
  Free_L: "Freelog",
  Free_R: "Freereg",
  CORP_R: "Corpreg",
  CORP_L: "Corplog",
  USER_L: "userlog",
  USER_R: "userreg",
  USER_HS: "userhome",
  USER_BI: "userbuy",
  USER_SI: "usersell", 
  HOME: "home",
});
